### PR TITLE
Added delete_record which can be used to delete archer object from an…

### PR DESCRIPTION
**Pull request by rafiifar**
… application

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
thank you for the pull request, have you tested this method on you archer instance?

**Review by ghost — COMMENTED** [review]
thank you for the pull request, have you tested this method on you archer instance?

**Comment by rafiifar** [comment]
Yes. I use it with archer 6.4 SP1P3

**Comment by ghost** [comment]
Awesome, thank you for your contribution )

**Pull request merged**
